### ISSUE TITLE
Request what you thought would be convenient

### ISSUE THREAD

**Issue by AngelSeed** [paissaheavyindustries/Lemegeton#3]
1. I thought it would be helpful if there was an ONOFF text command for the soft auto marker because it could be turned ON/OFF for different purposes.
2. I thought that if I could change the coordinates of the marker, it would be possible to cover it with the standard marker and not be invisible.

Always helpful, thank you for the wonderful Plugin. Thanks!

**Comment by paissaheavyindustries** [comment]
Thank you for your suggestions!

1) Could you give an example of what kind of a command did you have in mind? I'm thinking of something like:

/lemmy softmarkers on
/lemmy softmarkers off

Would that be good?

2) I can definitely implement multiple styles for people to choose from

**Comment by AngelSeed** [comment]
/lemmy softmarkers on
/lemmy softmarkers off

No problem at all. That helps a lot! ! !
I'm sorry for always being selfish like me!

**Comment by paissaheavyindustries** [comment]
No need to be sorry, they are good suggestions! Thank you for helping make Lemegeton better ☺️

**Comment by paissaheavyindustries** [comment]
Released in v1.0.11
