### ISSUE TITLE
Chinese font seems causing crash randomly on CN server

### ISSUE THREAD

**Issue by wozaiha** [paissaheavyindustries/Lemegeton#9]
When using the plugin with Chinese translation on CN server it randomly crashes Dalamud and it seems to be caused by the font. 

Not sure why this happens, but we use the same font in dalamud for default as the Chinese i18n use,maybe that's why it happens. 

After changing language to English manually, I have used it without crash over 2 hours.

**Comment by wozaiha** [comment]
[dalamud_appcrash_20230509_165334_099_31132.log](https://github.com/paissaheavyindustries/Lemegeton/files/11433072/dalamud_appcrash_20230509_165334_099_31132.log)

**Comment by paissaheavyindustries** [comment]
Thank you for your report - maybe it is some kind of a difference in how the CN Dalamud fork handles fonts, but I can't be sure as I don't have access to the CN version of the game at this time. If you would be able to help me out with testing a few different builds and changes to root out the problem, could you contact me on Discord at Locrian Mode#2318?

**Comment by paissaheavyindustries** [comment]
Sorted, thank you!
